version: '4' #versión de docker instalada
services:
  mysqldb: #El nombre que se le quiera dar al servicio
    image: mysql
    environment:
      - MYSQL_DATABASE=Base-datos-prueba
      - MYSQL_USER=user #puede ser cualquier nombre
      - MYSQL_PASSWORD=123
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 #permitir trabajar sin contraseña
    volumes:
      - "./backend/db:/docker-entrypoint-initdb.d" #sincroniza el script sql con mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysqldb #Mismo nombre del servicio de arriba
      - PMA_PORT=3306

# Eliminar volumen de mysql
# docker volume rm $(docker volume ls -q)
