version: '4' #versión de docker instalada
services:
  mysqldb: #El nombre que se le quiera dar al servicio
    image: mysql
    environment:
      - MYSQL_DATABASE=Base-datos-prueba
      - MYSQL_USER=user #puede ser cualquier nombre
      - MYSQL_PASSWORD=123
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 #permitir trabajar sin contraseña
    volumes:
      - "./backend/db:/docker-entrypoint-initdb.d" #sincroniza el script sql con mysql
    ports:
      - 3306:3306
    healthcheck: #verifica que servicio de mysql se esté ejecutando
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 0s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysqldb #Mismo nombre del servicio de arriba
      - PMA_PORT=3306

# Eliminar volumen de mysql
# docker volume rm $(docker volume ls -q)
  backend:
    depends_on:
      mysqldb:
        condition: service_healthy #para esperar que el servicio de mysql se esté ejecutando
        restart: true
    links:
      - mysqldb
    build: ./backend
    env_file: ./backend/.env
    ports:
      - 3000:3000
    environment:
      - DB_HOST=mysqldb
      - DB_USER=user
      - DB_PASSWORD=123
      - DB_NAME=Base-datos-prueba
      - DB_PORT=3306

  frontend:
    depends_on:
      mysqldb:
        condition: service_healthy
        restart: true
    links:
      - mysqldb
    build: ./frontend
    ports:
      - 4000:4000